#!/usr/bin/env python3
"""
generate-mirrors.py — Regenerate all platform command mirrors from the
single source of truth: .claude/commands/*.md

Outputs (committed to the repo — platforms read them at install time):

    .codex/prompts/<name>.md            # /<name> header + same body
    .opencode/commands/<name>.md        YAML frontmatter + same body
    .gemini/commands/<name>.toml        description + prompt=\"\"\"body\"\"\"
    .pi/extensions/tgd-commands.ts      templated TS, bodies JSON-embedded

Workflow:
    1. Edit .claude/commands/<name>.md ONLY. Never hand-edit a mirror.
    2. Run: python3 scripts/generate-mirrors.py
    3. Commit the source change together with the regenerated mirrors.

CI runs this script and fails the build if `git diff` is non-empty
afterwards (see .github/workflows/lint.yml, job "mirror-sync"), so a
hand-edited mirror or a forgotten regeneration cannot land on main.

Deterministic: same input always produces byte-identical output.
Python 3.8+ stdlib only. Exits non-zero with a precise message when a
command file cannot be encoded safely for a target format.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Dict, List, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = REPO_ROOT / ".claude" / "commands"
CODEX_DIR = REPO_ROOT / ".codex" / "prompts"
OPENCODE_DIR = REPO_ROOT / ".opencode" / "commands"
GEMINI_DIR = REPO_ROOT / ".gemini" / "commands"
PI_FILE = REPO_ROOT / ".pi" / "extensions" / "tgd-commands.ts"

# The 7 lifecycle commands, in pipeline order (drives pi registration order).
COMMANDS = [
    "tgd-map",
    "tgd-define",
    "tgd-plan",
    "tgd-develop",
    "tgd-verify",
    "tgd-review",
    "tgd-release",
]


def die(msg: str) -> None:
    sys.stderr.write(f"[generate-mirrors] ERROR: {msg}\n")
    raise SystemExit(1)


def parse_source(name: str) -> Tuple[str, str]:
    """Return (description, body) from .claude/commands/<name>.md.

    Expected layout:
        line 1: ---
        line 2: description: <text>
        line 3: ---
        line 4+: body (copied verbatim into every mirror)
    """
    path = SOURCE_DIR / f"{name}.md"
    if not path.is_file():
        die(f"source missing: {path}")
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    if len(lines) < 4 or lines[0].strip() != "---" or lines[2].strip() != "---":
        die(f"{path}: expected 3-line YAML frontmatter (---, description:, ---)")
    if not lines[1].startswith("description:"):
        die(f"{path}: line 2 must start with 'description:'")
    description = lines[1][len("description:"):].strip()
    if not description:
        die(f"{path}: empty description")
    body = "".join(lines[3:])
    return description, body


def check_toml_safe(name: str, description: str, body: str) -> None:
    if '"' in description or "\\" in description or "\n" in description:
        die(f"{name}: description contains characters unsafe for a TOML basic string")
    if '"""' in body:
        die(f'{name}: body contains \'"""\' which would terminate the TOML multi-line string')
    if "\\" in body:
        die(f"{name}: body contains a backslash, which TOML multi-line basic strings interpret as an escape")


def gen_codex(name: str, description: str, body: str) -> str:
    return f"# /{name}\n\n{description}\n{body}"


def gen_opencode(name: str, description: str, body: str) -> str:
    return f"---\ndescription: {description}\n---\n{body}"


def gen_gemini(name: str, description: str, body: str) -> str:
    return f'description = "{description}"\n\nprompt = """\n{body}"""\n'


PI_HEADER = """\
// tGD Pi Extension — Registers 7 lifecycle slash commands
// Compatible with pi-coding-agent 0.75.x
//
// AUTO-GENERATED by scripts/generate-mirrors.py from .claude/commands/*.md
// Do not edit by hand — edit the source command files and regenerate.

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const tgdPrompts: Record<string, string> = {
"""

PI_FOOTER_TEMPLATE = """\
}};

export default function (pi: ExtensionAPI) {{
  // Inject tGD rules at session start
  pi.on("session_start", async (_event, ctx) => {{
    ctx.ui.notify("tGD workflow loaded. Use /tgd-map to begin.", "info");
  }});

  // Register 7 lifecycle slash commands
  for (const [name, description] of [
{registrations}
  ] as [string, string][]) {{
    pi.registerCommand(name, {{
      description,
      handler: async (_args, ctx) => {{
        const prompt = tgdPrompts[name];
        if (prompt) {{
          ctx.ui.notify(`Running ${{name}}...`, "info");
          pi.sendUserMessage(prompt);
        }}
      }},
    }});
  }}
}}
"""


def gen_pi(entries: List[Tuple[str, str, str]]) -> str:
    """entries: [(name, description, body), ...] in COMMANDS order."""
    chunks = [PI_HEADER]
    for name, _description, body in entries:
        chunks.append(f"  {json.dumps(name)}:\n    {json.dumps(body, ensure_ascii=False)},\n")
    registrations = "\n".join(
        f"    [{json.dumps(name)}, {json.dumps(description, ensure_ascii=False)}],"
        for name, description, _body in entries
    )
    chunks.append(PI_FOOTER_TEMPLATE.format(registrations=registrations))
    return "".join(chunks)


def write_if_changed(path: Path, content: str, changed: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")
    changed.append(str(path.relative_to(REPO_ROOT)))


def main() -> int:
    entries: List[Tuple[str, str, str]] = []
    for name in COMMANDS:
        description, body = parse_source(name)
        check_toml_safe(name, description, body)
        entries.append((name, description, body))

    changed: List[str] = []
    for name, description, body in entries:
        write_if_changed(CODEX_DIR / f"{name}.md", gen_codex(name, description, body), changed)
        write_if_changed(OPENCODE_DIR / f"{name}.md", gen_opencode(name, description, body), changed)
        write_if_changed(GEMINI_DIR / f"{name}.toml", gen_gemini(name, description, body), changed)
    write_if_changed(PI_FILE, gen_pi(entries), changed)

    if changed:
        print(f"[generate-mirrors] Updated {len(changed)} file(s):")
        for c in changed:
            print(f"  {c}")
    else:
        print("[generate-mirrors] All mirrors already in sync.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
